# Site settings
title: Jayaram Prabhu Durairaj
email: bicepjai@gmail.com
description: "bicepjai's reverie"
baseurl: ""
# url: "http://bicepjai.github.io"
twitter_username: bicepjai
github_username: bicepjai

# Build settings
markdown: kramdown

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

port: 8081
