# Site settings
title: Scribbles With Intent
email: bicepjai@gmail.com
description: "bicepjai's reverie"
tagline: "Scribbles With Intent"
baseurl: ""
url: "http://bicepjai.com"
twitter_username: bicepjai
github_username: bicepjai

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
plugins:
  - jemoji

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

port: 8081
